name: Unix

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # Without MLPACK
          - {
            name: "macOS 10.15 AppleClang",
            mlpack: false,
            os: macos-10.15,
            cxx: "clang++",
            c: "clang"
          }
          - {
            name: "macOS 10.15 GCC 9",
            mlpack: false,
            os: macos-10.15,
            cxx: "g++-9",
            c: "gcc-9"
          }
          - {
            name: "Ubuntu 20.04 Clang 11",
            mlpack: false,
            os: ubuntu-20.04,
            cxx: "clang++-11",
            c: "clang-11"
          }
          - {
            name: "Ubuntu 20.04 GCC 10",
            mlpack: false,
            os: ubuntu-20.04,
            cxx: "g++-10",
            c: "gcc-10"
          }
          # With MLPACK
          - {
            name: "macOS 10.15 AppleClang",
            mlpack: true,
            os: macos-10.15,
            cxx: "clang++",
            c: "clang"
          }
          # - {
          #   name: "macOS 10.15 GCC 9",
          #   mlpack: true,
          #   os: macos-10.15,
          #   cxx: "g++-9",
          #   c: "gcc-9"
          # }
          - {
            name: "Ubuntu 20.04 Clang 11",
            mlpack: true,
            os: ubuntu-20.04,
            cxx: "clang++-11",
            c: "clang-11"
          }
          - {
            name: "Ubuntu 20.04 GCC 10",
            mlpack: true,
            os: ubuntu-20.04,
            cxx: "g++-10",
            c: "gcc-10"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Get macOS Concurrency
      if: runner.os == 'macOS'
      run: |
        echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV
        echo "Running on $(sysctl -n hw.ncpu) threads ..."

    - name: Get Linux Concurrency
      if: runner.os == 'Linux'
      run: |
        echo NPROC="nproc" >> $GITHUB_ENV
        echo "Running on $(nproc) threads ..."

    - name: Set Up macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install gcc@9

    - name: Set Up Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y cmake pkg-config clang-11 g++-10

    - name: Set Up macOS MLPACK
      if: runner.os == 'macOS' && matrix.config.mlpack
      run: |
        brew install mlpack
    
    - name: Set Up Linux MLPACK
      if: runner.os == 'Linux' && matrix.config.mlpack
      run: |
        sudo apt install -y libmlpack-dev libensmallen-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} -DCMAKE_C_COMPILER=${{matrix.config.c}} -DENABLE_MLPACK=${{matrix.config.mlpack}}

    - name: Build All
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC)

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j $($NPROC)
